# Generated by Django 4.1.7 on 2023-03-30 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=100, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['category_title'],
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_showing', models.IntegerField(blank=True, default=5, verbose_name='Частота показов')),
                ('script_url', models.URLField(verbose_name='Ссылка')),
                ('script_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('script_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('script_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lisovenkovaads_app.category', verbose_name='Категория сайта пользователя')),
            ],
            options={
                'verbose_name': 'Скрипт',
                'verbose_name_plural': 'Скрипты',
                'ordering': ['-script_created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads_title', models.CharField(blank=True, default='Рекламное объявление', max_length=100, verbose_name='Название объявления')),
                ('ads_showing', models.IntegerField(blank=True, default=5, verbose_name='Частота показов')),
                ('ads_url', models.URLField(verbose_name='Ссылка')),
                ('ads_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('ads_description', models.TextField(max_length=250, verbose_name='Описание')),
                ('ads_image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Изображение')),
                ('ads_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('ads_accept', models.BooleanField(blank=True, default=False, verbose_name='Принято')),
                ('ads_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('ads_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lisovenkovaads_app.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-ads_created_at'],
            },
        ),
    ]
